server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8067/eureka/

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #INDICA LE IMPOSTAZIONE PER IL ROUTER, CON ENABLED SI INDICA SE SI ABBILITA O MENO LA SCOPERTA DEI SERVIZI IN MODO DINAMICO
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-api/**
          filters:
            - RewritePath=/auth-api/(?<path>.*), /auth-api/$\{path}   #CHIEDERE A SCALZO SE IL "SIMPLE-API" DEVE RIMANERE O BISOGNA ASTRARRE LA CHIAMATA AL CLIENT

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG