server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8067/eureka/

spring:
  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # INDICA LE IMPOSTAZIONE PER IL ROUTER, CON ENABLED SI INDICA SE SI ABBILITA O MENO LA SCOPERTA DEI SERVIZI IN MODO DINAMICO
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-api/**
          filters:
            - RewritePath=/product-api/(?<path>.*), /product-api/$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-api/**
          filters:
            - RewritePath=/user-api/(?<path>.*), /user-api/$\{path}   # CHIEDERE A SCALZO SE IL "SIMPLE-API" DEVE RIMANERE O BISOGNA ASTRARRE LA CHIAMATA AL CLIENT

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://25.24.244.170:8080/realms/CaesarRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: caesar-app
      principal-attribute: admin

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG