server:
  port: 0

eureka:
  #  instance:                  #NELLA CONFIGURAZIONE N2 DEL CORS QUESTI VANNO OMESSI
  #    prefer-ip-address: true  #DICE AD EUREKA CHE PER ESSERE CONTATTATO (DA ALTRI SERVIZI) DI PREFERIRE IL SUO IP PIù TOSTO CHE IL SUO NOME [IN AMBIENTE DOCKER DOVREBBE ESSERE DI PREGIO]
  client:
    serviceUrl:
      defaultZone: http://localhost:8067/eureka/

spring:
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: saga-consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://25.24.244.170:8080/realms/CaesarRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  health:
    circuitbreakers:
      enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 4  #Numero di ultime chiamate tenute in cosiderazione dal circuit breaker
      permitted-number-of-calls-in-half-open-state: 5  #Numero massimo di tentativi concessi in fase di half-opened per capire se chiudersi o meno
      wait-duration-in-open-state: 20000  #Tempo in ms in cui il circuit breaker rimane in fase opened
      failure-rate-threshold: 50  #Numero percentuale di tentativi che devono fallire per aprirsi
      event-consumer-buffer-size: 10  #Numero di eventi salvati per strumenti terzi di valutazione (Actuator, ecc...)
      register-health-indicator: true
      record-exceptions:
        - org.springframework.web.client.RestClientException
        - org.springframework.web.client.ResourceAccessException
        - java.lang.IllegalArgumentException
        - java.io.IOException
        - java.net.SocketException
        - java.net.UnknownHostException
        - java.net.ConnectException
        - java.net.SocketTimeoutException
        - java.net.NoRouteToHostException

  instances:
    adminsService:
      base-config: default
    productService:
      base-config: default